# Header
logo_text: # Add text logo instead of logo image
menu:
  Home: /
  Categories: categories
  Tags: tags
  Archives: archives
  About: about

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png